[package]
name = "dtz-identity-auth"
version = "0.7.5"
edition = "2021"
authors = ["Jens Walter <jens@apimeister.com>"]
license = "Apache-2.0"
repository = "https://github.com/DownToZero-Cloud/dtz-identity-auth/"
description = "Provides authentication traits for DownToZero backends."

[dependencies]
serde = { version = "1", features = ["derive"] }
axum = { version = "0.6", features = ["http2","headers"] }
uuid = { version = "1", features = ["serde", "v4"] }
cookie = "0.17"
hyper = { version = "0.14", features = ["http1", "http2"] }
hyper-rustls = { version = "0.24", features = ["http1", "http2"] }
serde_json = "1"
serde_urlencoded = "0.7"
once_cell = "1.17"
lru_time_cache = "0.11"
jwt-simple = "0.11"
base64 = "0.21"