[package]
name = "dtz-identity-auth"
version = "0.2.0"
edition = "2021"
authors = ["Jens Walter <jens@apimeister.com>"]
license = "Apache-2.0"
repository = "https://github.com/DownToZero-Cloud/dtz-identity-auth/"
description = "Provides authentication traits for DownToZero backends."


[dependencies]
serde = { version = "1", features = ["derive"] }
axum = { version = "0.4", features = ["http2","headers"] }
uuid = { version = "0.8", features = ["serde", "v4"] }