[package]
name = "dtz-identity-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
axum = { version = "0.4", features = ["http2","headers"] }
uuid = { version = "0.8", features = ["serde", "v4"] }