name: pr
on:
  workflow_dispatch:
  pull_request:
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Rustfmt Check
      uses: actions-rust-lang/rustfmt@v1
    - name: Run clippy
      run: cargo clippy --all -- -D warnings
    - name: Cargo Test
      run: cargo test
    - name: Cargo MSRV
      run: |
        cargo install cargo-msrv --no-default-features
        cargo msrv verify
    - name: merge
      if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
      run: |
        gh pr merge --merge $GITHUB_HEAD_REF
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
